# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hypersycos
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Joshua Pollick'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
