# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hypersycos
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
baseurl:          ""

author:
  name:           'Joshua Pollick'
  url:            

paginate:         5

collections:
  warframe_reworks:
    output: true
    permalink: "/warframe-reworks/:name/"
    sort_by: date
  projects:
    output: true
    permalink: "/projects/:name/"
    sort_by: date
  sidebar:
    output: true
    permalink: "/:name/"
    sort_by: order

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
